### ISSUE TITLE
Gitlab link

### ISSUE THREAD

**Issue by hydrasho** [FreekBes/improved_intra#17]
add an option for add link to github or ``gitlab``

**Comment by FreekBes** [comment]
From version 3.0.4 onwards (which I will release tonight), you will be able to "convert" the GitHub link on your profile to a GitLab one by setting the value of _Your GitHub username_ to `gitlab@your_username` in the [extension's options page](https://darkintra.freekb.es/options.php).

Sample with a value of `gitlab@FreekBes`:
![image](https://user-images.githubusercontent.com/36384333/167000692-a634fe69-b8b3-4abc-ab05-cbf1fb625327.png)

Displaying both a link to one's GitHub **and** one's GitLab profiles, is not something I intend to add for now, as I think the UI would get too cluttered that way.
