### ISSUE TITLE
LOGTIME months hidden to right side on Show monthly logtimes/show cumulative logtimes per week

### ISSUE THREAD

**Issue by MisterTooh** [FreekBes/improved_intra#22]
**Describe the bug**
Logtimes (week/month) causes current month to be hidden on right side of the logtime section.

**To Reproduce**
1. Go to 'Settings'
2. Select  'Show monthly logtimes' and/or 'Show Cumulative logtimes per week'
3. Refresh Intra page
4. See 'LOGTIME' on intra

**Expected behavior**
Show as normal but with Cumulative and/or Monthly Logtimes. Current Month is MAY 2022 but it is hidden.

**Screenshots**
<img width="617" alt="Screen Shot 2022-05-10 at 4 55 53 PM" src="https://user-images.githubusercontent.com/55613401/167633383-025dd04b-c322-4032-94f2-9543039512c1.png">

**HTML source code**
(cannot upload .html file)
[intra_src_code.txt](https://github.com/FreekBes/improved_intra/files/8661703/intra_src_code.txt)

**Desktop information (please complete the following information):**
 - OS: macOS Catalina (within 42 Campus)
 - Browser: Google Chrome Version 92.0.4515.131 (Official Build) (x86_64)

**Comment by FreekBes** [comment]
Thanks for the bug report. However, I am unable to reproduce this issue. Could this have anything to do with the timezone of a campus maybe?

The reason this happens is because here at my campus (Amsterdam), we run into the issue where sometimes the months are shifted to the left by Intra, so I shift them back to the right. Apparently then, this doesn't happen to all campuses...

Sadly, while you included the source code, the viewbox attribute was missing on the logtime chart element. It seems this attribute is generated after loading the page. If this bug were to occur again, can you comment the contents of this attribute here? You should be able to get those by running the following snippet of code in the Javascript console: `document.getElementById("user-locations").getAttribute("viewBox")`.

**Comment by MisterTooh** [comment]
Hello, here you go! I think that since our campus doesn't face that issue with shifting left, it might just be that!

```
document.getElementById("user-locations").getAttribute("viewBox")
"0 0 600 200"
```

<img width="553" alt="Screen Shot 2022-05-23 at 5 27 34 PM" src="https://user-images.githubusercontent.com/55613401/169830272-e3e5a484-a507-4375-891e-cd2dd0de4e64.png">

**Comment by FreekBes** [comment]
That's interesting! Here, when I have a viewBox with exactly these attributes, everything looks to be okay. Now I'm very confused...

<img width="1764" alt="Screen Shot 2022-05-23 at 6 40 02 PM" src="https://user-images.githubusercontent.com/36384333/169867504-d71fdefb-f29b-4366-967e-b0575c183ba5.png">

I guess I'll have to investigate a bit more, maybe there's an additional setting applied to the element elsewhere that causes the shift. Thanks for this interesting bug report so far.

**Comment by 0xPacman** [comment]
I have the same problem, the issue is only there because of the theme `vela` if you change it it will appear normal.

**Comment by MisterTooh** [comment]
> I have the same problem, the issue is only there because of the theme `vela` if you change it it will appear normal.

Unfortunately the problem persists. I've played around with different themes, and light/dark mode, and the issue is persistent.

**Comment by FreekBes** [comment]
Found the source of the issue, no additional option is needed!

It appears all of the coordinates of the SVG elements are sometimes shifted 150 pixels to the right, and Intra tries to compensate for that by shifting everything 150 pixels to the left, which then causes the extension to add an additional 150 pixels to this shift. I've fixed this issue by looking for the x-coordinate of the first text-element of the SVG, and only applying the fix if the x value is less than 150.

Thanks again for reporting!

**Comment by FreekBes** [comment]
Additionally, today I found out why Intra shifts the logtime chart at all. Here's 5 months being displayed instead of the regular old 4.

<img width="710" alt="image" src="https://user-images.githubusercontent.com/36384333/170949670-c1c5b7fd-a9b0-45e9-865d-1602f80db060.png">
