### ISSUE TITLE
Other hosting platform link

### ISSUE THREAD

**Issue by LeafyOtter** [FreekBes/improved_intra#25]
I think it could be pretty cool if we could add our username on other git-based hosting platform (especially self-hosted one).
A few exemple would be gitea, sourcehut or gogs, to name only a few.

**Comment by LeafyOtter** [comment]
I don't think i have any sample URLs.

**Comment by harm-smits** [comment]
@FreekBes We could set up a little warnign on the server side telling people that they are being redirected to an unknown third party website and to proceed with caution, whereas this warning would not show with github, gitlab and sourcehut.

**Comment by LeafyOtter** [comment]
I think it would be a great way to incorporate it

**Comment by FreekBes** [comment]
@harm-smits sounds like a plan. Currently different services are saved in a specific format: `service@username`. I'm not sure currently how to implement third party services in that manner, but maybe a good time to implement that would be with a complete serverside rewrite. I'm planning on doing that in the near future.

**Comment by harm-smits** [comment]
The services would be rather easy to handle. We can use PHP's `parse_url` to grab just the hostname + url path. This way no funky stuff can happen really. Of course we also enforce HTTPS.

**Comment by FreekBes** [comment]
Status update! I just finished writing the new back-end for the extension, where git usernames will instead be stored in the following format in the new DB: `domain@username`. So `github.com@FreekBes` or `gitlab.com@FreekBes`. This way we can whitelist new domains and add functionality for those domains on the client-side, making sure only git services are linked this way.

Additionally, I plan on also including a 'portfolio' link on profiles, where you can basically link any website you want.

These changes will be rolled out once the front-end has been rewritten to work with the new back-end, so probably within a month.

**Comment by Vusk42** [comment]
Hey! Is it possbile to add https://codeberg.org/ profile's link ?
It is powered by Gitea

**Comment by FreekBes** [comment]
This feature has been added in release v4.0.0: https://github.com/FreekBes/improved_intra/releases/tag/v4.0.0
