### ISSUE TITLE
Add a "how many points are in the pool" counter

### ISSUE THREAD

**Issue by SirMorfield** [FreekBes/improved_intra#33]
A good place would be in the 
```
Wallet
Evaluation
Cursus
Grade
```
div.

This was not my idea.

**Comment by FreekBes** [comment]
The Pool API endpoints are locked behind staff tokens, meaning their balances cannot be fetched for Improved Intra.
See https://api.intra.42.fr/apidoc/2.0/balances/index.html

**Comment by SirMorfield** [comment]
Better late than never
