### ISSUE TITLE
Change first day of the week of the log time calendar.

### ISSUE THREAD

**Issue by TalviT** [FreekBes/improved_intra#41]
Request:
Represent the log time calendar with Monday as first day of the week.

This could be archived by rearranging the rectangles of the calendar SVG element, by manipulating their x and y values.
This feature should probably be a setting, to make the change optional.

Additional notes:
Since in some areas in the world, the first day of the week is Saturday, a third option or a free selection for day could also be an option (but might be more complex).
The default setting could be set depending on the user's locale.

**Comment by FreekBes** [comment]
This will be added in the next Improved Intra update. It won't be a setting in the Improved Intra settings - the extension will take the computer's localization settings into account
