### ISSUE TITLE
add Image requirements to the upload menu

### ISSUE THREAD

**Issue by RoyaLProg** [FreekBes/improved_intra#44]
I am trying for 30 minutes now to upload my image and it wont work !
I tried resizing it, changing the name, the format and everything and I don't know why it wont work

If it is possible to add the requirement and format accepted to the images it would be fantastic

If not, put them on the github readme maybe ?

In anyway i'll contimue trying putting my image x_x

(this one) https://imgur.com/MYYtwkP
![wallpaper](https://user-images.githubusercontent.com/63088010/202337672-bd45ee0f-b893-4cda-974b-548e6559aa47.jpg)

**Comment by FreekBes** [comment]
In the next update of Improved Intra, v4.0.0, this has been added. It is however not ready for release just yet. Soon™!
