### ISSUE TITLE
remove "Feedbacks Logs" buttons

### ISSUE THREAD

**Issue by leeoocca** [FreekBes/improved_intra#45]
**Describe the bug**
This feature has been added to the Intranet.

**To Reproduce**
...

**Expected behavior**
...

**Screenshots**
![image](https://user-images.githubusercontent.com/36135198/203344987-c9fe0e4f-ef67-4859-ad4f-9c55ce9b2417.png)

**HTML source code**
...

**Desktop information (please complete the following information):**
 - OS: not relevant
 - Browser: not relevant

**Comment by FreekBes** [comment]
This was fixed in commit #7c5bd298f301e44b89ae3b0ab432943f424fbcfc and will be released in the next update
