### ISSUE TITLE
Coalition screen text almost invisible on dark mode

### ISSUE THREAD

**Issue by YastMe** [FreekBes/improved_intra#58]
Usernames and points gained by users for their coalitions show as black text on a black/grey background.

**Screenshots**
<img width="2479" alt="Screen Shot 2023-08-01 at 10 46 26 AM" src="https://github.com/FreekBes/improved_intra/assets/64034487/35024158-98b3-4957-8c65-7d4aef6197fa">

**Expected behavior**
Text should be at least visible (white or any light color)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Extension version: 4.1.0

**HTML source code**
[Intra Profile Void.txt](https://github.com/FreekBes/improved_intra/files/12226469/Intra.Profile.Void.txt)

**Comment by FreekBes** [comment]
This has to do with the fact that your coalition's theme color is set to black. This is not a bug with Improved Intra.
