### ISSUE TITLE
Cannot change background

### ISSUE THREAD

**Issue by Xylo-o** [FreekBes/improved_intra#79]
**Describe the bug**
Since last intra updates it's not possible to change background on the profile.

**To Reproduce**
1. Go to 'Extension settings'
2. Click on 'Edit profile'
3. Custom profile banner -> choose file and load it
4. Save settings
5. See error : 'Error while saving settings: SyntaxError: Unexpected token '<',
"<html>
<h"... is not valid JSON'

**Desktop information (please complete the following information):**
 - OS: Windows 10/ Mac OS
 - Browser: Google Chrome
 - Extension version: 4.3.1<!DOCTYPE html>

**Comment by FreekBes** [comment]
Hello, thank you for your bug report.

What type of image extension did you try to upload and what was the file's size in bytes?

**Comment by Xylo-o** [comment]
I've reinstalled extension and now it showed error message 'File too large' for file 10,7MB.

Then I tried with a bit compressed file ~9,7MB and it works.

Thanks for reply though 👍

**Comment by pibouill** [comment]
Having the same issue with images way lighter than 9MB, tried different formats as well as reinstalling the extension.

After setting up the background in the settings, it says "No file chosen" next to the file selection button - even though the image is properly displayed above
