### ISSUE TITLE
Cumulative hours when codam's monitoring system is disabled.

### ISSUE THREAD

**Issue by TheBriar** [FreekBes/improved_intra#8]
Disabling "Replace black hole with Codam's monitoring progress should not remove cumulative hours from the hover menu. The percentage can be removed though.
![image](https://user-images.githubusercontent.com/86962846/144330468-5bccebe6-df2f-4934-a500-846dd114696b.png)

**Comment by FreekBes** [comment]
Just a heads-up, I'm still thinking about implementing this, but it would require a lot of work internally so I haven't started on it yet. It's still on the todo-list though!
