### ISSUE TITLE
Cluster position in profile is no longer a link

### ISSUE THREAD

**Issue by kde-la-c** [FreekBes/improved_intra#80]
**Describe the bug**
The cluster position on profiles is no longer clickable open the cluster's map

**To Reproduce**
1. Enabled the option **Make logged in location clickable** in the settings
2. Reloaded profile page
3. Link doesn't work, no particular error, it just isn't in the HTML

**Screenshots**
![image](https://github.com/FreekBes/improved_intra/assets/47521496/6e17240b-01c1-467e-935b-6e56c56a039f)
![image](https://github.com/FreekBes/improved_intra/assets/47521496/1601e245-257d-4c51-8ca4-496205bbdb4f)
![image](https://github.com/FreekBes/improved_intra/assets/47521496/4be81db8-3c9a-4027-ae7a-1faea0770793)

**Desktop information (please complete the following information):**
 - Current server version: 3.3.0
Server target version: 4.2.0
Extension version: 4.3.1
Browser: Chrome 124.0.0.0
OS: Linux undefined

**Comment by FreekBes** [comment]
I cannot seem to reproduce this bug, can you confirm this is still happening?
